#spring:
#  profiles:
#    active: @spring.profiles.active@
#
#app:
#  datasource:
#    jdbc-url: jdbc:postgresql://localhost:5432/spring_react1
#    username: postgres
#    password: password
#    pool-size: 30

#spring:
#  profiles:
#    active: demo

server:
  port: 5000

app:
  datasource:
    jdbc-url: jdbc:postgresql://ec2-54-75-231-215.eu-west-1.compute.amazonaws.com:5432/dd1r5229mjn6ag
    username: zqdmilfnkidigp
    password: a20a036e4b0ff405ddc8fe8ac2a96cab424fd847838a40352801b00eccd892be
    pool-size: 30
